### ISSUE TITLE
[BUG] Disabling an ability while having a different ability of the same name causes errors

### ISSUE THREAD

**Issue by StrangeOne101** [Simplicitee/ProjectAddons#20]
**Describe the bug**
Pretty simple. When you disable a ProjectAddons ability, and have an ability with the same name on the server, it's errors gallore.

**To Reproduce**
1. Disable LavaSurge
2. Install beta LavaSurge from PK
3. Use LavaSurge
4. ~~Profit~~ Die of errors

**Expected behavior**
No errors :D

**Versions:**
 - Spigot: 1.19.3
 - ProjectKorra 1.11.0 BETA4
 - ProjectAddons 1.2.3

**Logs**
```
[09:12:59 ERROR]: Could not pass event PlayerToggleSneakEvent to ProjectAddons v1.2.3
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getTargetBlock(java.util.Set, int)" because "this.player" is null
        at me.simplicitee.project.addons.ability.earth.LavaSurge.prepare(LavaSurge.java:89) ~[ProjectAddons-1.2.3.jar:?]
        at me.simplicitee.project.addons.ability.earth.LavaSurge.<init>(LavaSurge.java:83) ~[ProjectAddons-1.2.3.jar:?]
        at me.simplicitee.project.addons.MainListener.onSneak(MainListener.java:250) ~[ProjectAddons-1.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor526.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-409]
```

**Comment by ArifKalender** [comment]
Same thing goes with EarthKick too. I have Jedcore & ProjectAddons installed on my server and when I disable ProjectAddons earthkick same error occurs. 

**Spigot:** Paper 1.18.2
**ProjectKorra:** 1.11.0
**JedCore:** 2.12.1-Spigot1.18-PK1.10.2
**ProjectAddons:** 1.2.4

*Edit: Forgot to include the error message.
Error message: https://pastebin.com/kcKCKZEg
